### ISSUE TITLE
Convert to a consistent quote use: double or single

### ISSUE THREAD

**Issue by jdalton** [seidtgeist/syntux#17]
Syntux should convert to a consistent quote use: double or single.
For the case of our stuff `single`.

**Comment by seidtgeist** [comment]
This? https://github.com/evilhackerdude/syntux/blob/master/test/integration/test-quotes.js

**Comment by jdalton** [comment]
It is possible... made the ticket because one of the Syntux passes in our Uxebu projects didn't catch the double quote.

**Comment by seidtgeist** [comment]
Oh, it is probably disabled so it doesn't interfere with intentionally double-quoted strings, i.e., strings with single quotes inside them.

Possibly, but highly unlikely, the deployed quotes plugin is in an outdated version.
