### ISSUE TITLE
Take apart and re-assemble jQuery

### ISSUE THREAD

**Issue by felixge** [seidtgeist/syntux#2]
This will need a bunch of hacking on ZeParser (to give us all whitespace / comment info) as well as creating the AST -> code stuff.

Goal: Parse jQuery into an AST and put it back together _exactly_ how it was before.

Once we can do this, we should be able to start hacking on the syntux rules & algorithms!

**Comment by seidtgeist** [comment]
I agree, we should set up a test which does exactly that and shows the diff between original and reproduction in some way.

**Comment by felixge** [comment]
> I agree, we should set up a test which does exactly that and shows the diff between original and reproduction in some way.

I'll add this to the repo later tonight.

For the diff I'll probably just shell out to the unix `diff` utility : ).

**Comment by seidtgeist** [comment]
Which reminds me that I should write a diff web service that produces output as awesome as p4merge’s.
