### ISSUE TITLE
Narrow down the usecase of syntux

### ISSUE THREAD

**Issue by klipstein** [seidtgeist/syntux#3]
In the README.md there is a mention that syntux should also include warnings if classes, functions and constants aren't named as defined in the coding styles. I would remove these lines from the README as it gives the notion that it will also check the code for inconsistencies.

Maybe a good rule would be, that syntux is a tool for changing code when it is able to modify it without changing the original behaviour of it. For now I would try to avoid outputting warnings of possible coding style conflicts, as they could lead to a huge list of configuration options for the syntux/config.json file.

I could help out defining the syntux configuration file.

**Comment by klipstein** [comment]
An initial version of how the configuration could look like:

```
{
  "indentation": "    ", // or \t
  "quoteStyle": "single", // or double
  "lineEndingStyle": "\n",
  "addMissingSemicolons": true,
  "removeTrailingWhitespace": true,
  "appendNewLineAtEof": true,
}
```

Spacing between assignments, loops and function declarations is not defined yet as this could get quite complex.

**Comment by felixge** [comment]
I think we could do warnings, but have them disabled by default / turn them on with a config switch. Not sure.

But yeah, initially we should focus on just transforming code. Your config looks ok, but I may prefer shorter property names like:

``` js
{
  "quotes": "'",
  "indent": "  ",
}
```

--fg

**Comment by seidtgeist** [comment]
+1 to shorter names and no warnings - for now there’s jshint

**Comment by klipstein** [comment]
I've used these explanatory names mostly because it is a configuration file, where readability is more important than writeability. But I also would be for shorter names, if it is immediately clear what is meant by it. This could be a proposal for shorter config options:

```
{
  "indent": "    ", // or \t
  "quotes": "single", // or double
  "lineEndings": "\n",
  "asi": true,
  "trailingWhitespace": false,
  "eof": "\n",
}
```

**Comment by felixge** [comment]
>  `"asi": true,`

I suppose this stands for automatic semicolon insertion? Why not `"semicolons": true`

Otherwise this LGTM. We will probably want more options, but this seems like a good base set to initially implement.

**Comment by seidtgeist** [comment]
Another idea:

```
"header": "path/to/license"
```

or something like that :)

**Comment by felixge** [comment]
```
"header": "8========D~~~~~"
```

: )

**Comment by seidtgeist** [comment]
![ASCIIDICK ALL THE FILES](http://memegenerator.net/cache/instances/400x/10/10712/10969939.jpg)

**Comment by klipstein** [comment]
I'm just sitting in front of implementing some more plugins for syntux and I am currently looking into whitespacing / brace-styling. For inspiration I've looked into http://jalopy.sourceforge.net/existing/whitespace.html and http://jalopy.sourceforge.net/existing/braces.html.

Different brace styles could be defined with the following configuration:

``` json
{
  /* definition as array (cStyle) */
  "braces": ["{", "\n}"],
  /* or: definition as array (sunStyle) */
  "braces": ["\n{", "\n}"],
  /* or: definition as array (gnuStyle) */
  "braces": ["\n  {", "\n  }"],
  /* or: defintion by name */
  "braces": "cStyle" /* or: "sunStyle", "gnuStyle" */
}
```

The configuration for whitespaces could look like that (value not defined = don't touch the whitespacing, true = add whitespace(s), false = remove whitespace(s)):

``` json
{
  "whitespace": {
    "spaceBefore": {
      "methodDeclaration": true, /* false */
      "methodCall": true,
      "statement": true,
      "braces": true,
      "brackets": true,
      "caseColon": true
    },
    "spaceAfter": {
      "comma": true,
      "semicolon": true,
      "logicalNot": true
    },
    "spacesAround": {
       "assignmentOp": true,
       "logicalOp": true,
       "relationalOp": true,
       "bitwiseOp": true,
       "mathOp": true,
       "shiftOp": true,
       "braces": true,
       "brackets": true,
       "parantheses": true
    }
}
```

To configure it more easily we could define some common configuration-sets (same as with `braces` above):

``` json
{
  "whitespace": "nodeStyle",
  /* or */
  "whitespace": "dojoStyle"
}
```

**Comment by seidtgeist** [comment]
When designing plugins I focus on simplicity:
- Simple mapping between config and cli options
- Simple to remember plugin names (= short, unambiguous)
- Plugins should be focused
- Plugins should do as little as possible

Array options make the 1:1 mapping between configuration and cli harder to remember. Of course we could do sth like:

```
--whitespace-spaceBefore-braces
```

**Edit:** Forgot to mention that array-values could be tricky:

```
--braces ['lol', 'shell',' array', 'pls', 'no']
```

But too many of these options will probably defeat our purpose of simplicity.

I liked the idea of presets very much though:

```
--braces c
--braces node
--braces gnu
--whitespace node
--whitespace dojo
```

Also: in the future we could think about allowing custom presets or advanced options.

**Comment by felixge** [comment]
+1 on presets and simple cli options

**Comment by seidtgeist** [comment]
Archiving this as we have a bunch of finely grained issues which came out of this.
